# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappfinancialinclusionchems

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerfinancialinclusionchems.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0c9cf62e3b744f1a1bcf9f3dcb21511 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3a98dad436844dcb9aa6a77d549115a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerfinancialinclusionchems.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0c9cf62e3b744f1a1bcf9f3dcb21511 }}/containerfinancialinclusionchems/financial_inclusion_api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappfinancialinclusionchems'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d3affd7413cf44549e705b5d74d476e1 }}
        images: 'containerfinancialinclusionchems.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0c9cf62e3b744f1a1bcf9f3dcb21511 }}/containerfinancialinclusionchems/financial_inclusion_api:${{ github.sha }}'